version: "3.0"
services:
    mysql:
        container_name: mysql
        image: mariadb
        volumes:
            - /home/mcg/Docker/MySQL:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
        mem_limit: 1g
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        ports:
            - "25511:80"
        environment:
            - PMA_HOST=mysql
        mem_limit: 128m
    minecraft:
        container_name: minecraft
        build: .
        depends_on:
            - mysql
        ports:
            - "25565:25565"
        volumes:
            - /home/mcg/Servers:/home/mcg/Servers
            - /home/mcg/ResourcePack:/home/mcg/ResourcePack
        mem_limit: 48g
    mcghttp:
        container_name: mcghttp
        image: node:14-alpine
        depends_on:
            - mysql
        ports:
            - "25599:25599"
        volumes:
            - /home/mcg/HTTPServer:/server
            - /home/mcg/ResourcePack:/resourcepack
        working_dir: /server
        entrypoint: node app.js
        mem_limit: 128m
