CREATE TABLE IF NOT EXISTS `scores` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`season` INT NOT NULL,
	`uuid` VARCHAR(255) NOT NULL,
	`minigame` VARCHAR(255) NOT NULL,
	`score` INT NOT NULL,
	`metadata` VARCHAR(255),
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE KEY (`season`, `uuid`, `minigame`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `teams` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`season` INT NOT NULL,
	`teamname` VARCHAR(255) NOT NULL,
	`color` VARCHAR(255) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `players` (
	`uuid` VARCHAR(255) NOT NULL,
	`season` INT NOT NULL,
	`username` VARCHAR(255) NOT NULL,
	`teamid` INT UNSIGNED,
	PRIMARY KEY (`uuid`,`season`) USING BTREE,
	FOREIGN KEY (`teamid`) REFERENCES `teams` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `logs` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`season` INT NOT NULL,
	`minigame` VARCHAR(255) NOT NULL,
	`playeruuid` VARCHAR(255) NOT NULL,
	`scoredelta` INT NOT NULL,
	`message` VARCHAR(255) NOT NULL,
	`timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET=utf8mb4;
